name: build_pysrc
on:
  push: {tags:  ['v*'] } # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request: 

permissions:
  contents: write

jobs:
  test_pysrc:
    runs-on: ubuntu-22.04
    steps:
    - name: pull and init
      uses: actions/checkout@v3
      with: {submodules: true}

    - name: make enviroment
      run: |
        sudo apt-get update && sudo apt-get install p7zip-full
        pip install python-docx # ftextcvt
        pip install numpy numba pillow
        pip install scikit-learn

    - name: test pysrc
      run: |
        chmod +x project/pysrc_all/*.sh
        bash project/pysrc_all/test_pyunit.sh

    - name: test pycli
      run: |
        chmod +x project/pysrc_all/*.sh
        source project/pysrc_all/test_pycli.sh && test_all

  build_pysrc:
    runs-on: ubuntu-22.04
    steps:
    - name: pull and init
      uses: actions/checkout@v3
      with: {submodules: true}

    - name: make enviroment
      run: |
        sudo apt-get update && sudo apt-get install p7zip-full
        pip install python-docx # ftextcvt
        pip install numpy numba pillow
        pip install scikit-learn
    
    - name: build pysrc
      run: |
        chmod +x project/pysrc_all/*.sh 
        bash project/pysrc_all/build_pysrc.sh
        bash project/pysrc_all/test_pydep.sh
        cd project/pysrc_all
        rm -rf build/__pycache__
        archive_name=LocalizationPytool_${{ github.ref_name }}
        7z a ${archive_name}.7z build
        7z rn ${archive_name}.7z build ${archive_name}

    - name: create a release
      uses: ncipollo/release-action@v1
      if: github.event_name == 'push'
      with:
        artifacts: "project/pysrc_all/*.7z"
        allowUpdates: "true"
        token: ${{ secrets.GITHUB_TOKEN }}